#version: '3'
#services:
#  your-service:
#    build:
#      context: .    # The path to the directory containing the Dockerfile
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"  # Map host port to container port
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/your_database_name
#      SPRING_DATASOURCE_USERNAME: your_db_username
#      SPRING_DATASOURCE_PASSWORD: your_db_password
#    depends_on:
#      - database
#
#  database:
#    image: mysql:latest
#    ports:
#      - "3306:3306"  # Map host port to container port
#    environment:
#      MYSQL_ROOT_PASSWORD: your_mysql_root_password
#      MYSQL_DATABASE: your_database_name
#      MYSQL_USER: your_db_username
#      MYSQL_PASSWORD: your_db_password


version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: AmigosUnitTest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password