version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: AmigosUnitTest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 30496039