version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: AmigosUnitTest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 30496039

  clustered-data-warehouse:
    build:
      context: ./path/to/your/build/context
      dockerfile: Dockerfile
    ports:
      - "8080:8080"